// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.23.8";
var services = [
  {
    category: "Consultoria, diagn\xF3stico e organiza\xE7\xE3o empresarial",
    items: [
      { name: "Raio-X de Gargalos Operacionais", price: "A partir de R$ 600" },
      { name: "Organiza\xE7\xE3o Comercial e Atendimento", price: "A partir de R$ 1.800" },
      { name: "Mapeamento de Processos", price: "A partir de R$ 1.500" },
      { name: "Estrutura\xE7\xE3o de Equipes e Rotinas", price: "A partir de R$ 1.500" },
      { name: "Implanta\xE7\xE3o de Melhorias Operacionais", price: "A partir de R$ 1.800" }
    ]
  },
  {
    category: "Presen\xE7a digital",
    items: [
      { name: "Google Essencial", price: "R$ 300" },
      { name: "P\xE1gina Expressa", price: "R$ 500" },
      { name: "Kit Presen\xE7a Local", price: "R$ 800" },
      { name: "Estrutura Digital de Entrada", price: "A partir de R$ 600" },
      { name: "Ajustes Estrat\xE9gicos de Apresenta\xE7\xE3o", price: "A partir de R$ 400" }
    ]
  }
];
var list_services_default = defineTool({
  name: "list_services",
  title: "List services",
  description: "List the services and prices offered by Astro Consultoria.",
  inputSchema: {
    category: z.enum(["all", "consulting", "digital"]).optional().describe("Filter by category. Defaults to 'all'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const filtered = category === "consulting" ? [services[0]] : category === "digital" ? [services[1]] : services;
    return {
      content: [{ type: "text", text: JSON.stringify(filtered, null, 2) }],
      structuredContent: { categories: filtered }
    };
  }
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_contact_default = defineTool2({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Return the contact channels for Astro Consultoria (WhatsApp, email, site).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      company: "Astro Consultoria",
      whatsapp: "+55 51 98152-0555",
      whatsapp_link: "https://wa.me/5551981520555",
      email: "astroconsultorias@gmail.com",
      site: "https://astroconsultorias.com.br"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var whoami_default = defineTool3({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in Astro Consultoria account for the current MCP session.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const data = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wzjusrxpcuwqbrjrkayt";
var mcp_default = defineMcp({
  name: "astro-consultoria-mcp",
  title: "Astro Consultoria",
  version: "0.1.0",
  instructions: "Ferramentas da Astro Consultoria: consulte os servi\xE7os e pre\xE7os, obtenha os canais de contato oficiais e identifique a conta autenticada.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_services_default, get_contact_default, whoami_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
